### ISSUE TITLE
Butler Volmer in Cantera

### ISSUE THREAD

**Issue by decaluwe** [coresresearch/BatCan#2]
Is it ready?  What are the to-do-items remaining?

**Comment by decaluwe** [comment]
Hey @c-randall - can you add some figures to this issue to demonstrate the functionality, preferably before today's meeting?  Thanks!

**Comment by c-randall** [comment]
![image](https://user-images.githubusercontent.com/39809042/61738006-97f14c00-ad46-11e9-8525-31a4477395a2.png)

![image](https://user-images.githubusercontent.com/39809042/61738083-bbb49200-ad46-11e9-94dd-744455c091aa.png)

![image](https://user-images.githubusercontent.com/39809042/61738138-d7b83380-ad46-11e9-88ba-f7c63b996dba.png)

![image](https://user-images.githubusercontent.com/39809042/61738882-8315b800-ad48-11e9-8171-2aa4c3c6dcd1.png)

![image](https://user-images.githubusercontent.com/39809042/61738918-96288800-ad48-11e9-9531-fec529f251ad.png)
